### ISSUE TITLE
[suggestion] use metadata.annotations['<KEY>']

### ISSUE THREAD

**Issue by voelzmo** [gardener-samples/kube-featureflag#3]
Hey, it seems the javascript code currently needs to contain some ugly logic to remove the quotation marks from the `annotations` file. This would be unnecessary, if we mounted the annotations value into a separate volume
```
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "annotations/businessFeature"
            fieldRef:
              fieldPath: metadata.annotations['businessFeature']
```
source: https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

Is there a specific reason not to do this? Having multiple feature flags this would result in multiple files being parsed – not sure what the tradeoff here is.
